const botonEmpezar = document.querySelector("#btn-inicio")
const botonSiguiente = document.querySelector("#btn-siguiente")
const contenedorPreguntas = document.querySelector("#contenedor-preguntas")
const cadaPregunta = document.querySelector("#pregunta")
const opcionRespuestas = document.querySelector("#btn-respuestas")
const contenedorGrafico = document.querySelector("#contenedor-grafico")
const contenedorResultado = document.querySelector("#contenedor-resultados")